[package]
name = "basex"
version = "0.1.0"
authors = ["Roman Hodulák <hodulakr@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A client library for BaseX XQuery databases."
repository = "https://github.com/RomanHodulak/basex_client"
readme = "README.md"
categories = ["database"]
keywords = ["database", "basex", "xml", "xquery", "xpath"]

[dependencies]
md5 = "0.6.1"

[dev-dependencies]
matches = "0.1.8"
rust-embed = "5.9.0"
