[package]
name = "basex"
version = "0.4.0"
authors = ["Roman Hodulák <hodulakr@gmail.com>"]
edition = "2018"
license = "ISC"
description = "A client library for BaseX XQuery databases."
repository = "https://github.com/RomanHodulak/basex_client"
readme = "README.md"
categories = ["database"]
keywords = ["database", "basex", "xml", "xquery", "xpath"]
include = [
    "src/**/*.rs",
    "tests/",
    "Cargo.toml",
]

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items"]

[dependencies]
md5 = "0.6.1"

[dev-dependencies]
matches = "0.1.8"
rust-embed = "5.9.0"
circbuf = "0.2.0"
