[package]
name = "basex_client"
version = "0.1.0"
authors = ["Roman Hodulák <roman@hodulak.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.6.1"
matches = "0.1.8"
rust-embed = "5.9.0"
