version: "3.7"
services:
    basex:
        image: basex/basexhttp:9.5.2
        container_name: basex-basex
        volumes:
            - ./docker/data:/srv/basex/data
            - ./tests/files:/tmp/files
        environment:
            - BASEX_JVM=-Xmx1g
        ports:
            - 1984:1984
            - 8984:8984
            - 8985:8985
